### ISSUE TITLE
S2 x-y correction should be applied in basics

### ISSUE THREAD

**Issue by coderdj** [XENON1T/hax#103]
We want to start migrating corrections from pax to hax wherever possible. Since it seems like pax is skipping the x-y correction anyway, we can start with that one as a test case.

This update should set a basic framework for applying up-to-date corrections similar to how it is done in cax. This should be relatively easy for all the multiplicative area corrections.

**Comment by adambrown1** [comment]
We probably want to put the corrections in a minitree other than basics (see also issue #101).

For now, since the correction files are already stored in pax, I suggest to just get the name of the file from the DB and take the data itself from pax. Then we can implement this rather easily and quickly so that analysts can get on with using S2-corrected data.

**Comment by pdeperio** [comment]
Fixed in #109
