### ISSUE TITLE
Extending Corrections Minitrees to Work with MC simulations

### ISSUE THREAD

**Issue by jpienaar13** [XENON1T/hax#139]
Update to hax v1.6.2 caused problems in the production of minitrees for MC studies. (See #135). This has been temporarily circumvented by reverting to the last working hax commit (aadb15b) CVMFS.

Moving forward we will need an implementation  of a config option for all run dependent parameters that allows input for MC simulations to be set.

**Comment by pdeperio** [comment]
Any decision yet on how to move forward with this?  Issue https://github.com/XENON1T/hax/issues/135 is technically still open, i.e. hax still not synced between data (Midway) and MC (CVMFS), and we should get this fixed ASAP since ```v6.8.0``` reprocessing is finishing.

I tried to start something coarse (science run variation) and basic in https://github.com/XENON1T/pax/pull/610, where you can use ```event.dataset_name``` (containing the string "MC") as a flag to determine what to do in [corrections.py](https://github.com/XENON1T/hax/blob/master/hax/treemakers/corrections.py).  But then here can you read in those new pax configs (```SR0_parameters.ini``` or ```SR1_parameters.ini```) and use it to set the e-lifetime (```elife_interpolation```) and all the correction maps (```get_lce_map_name ```: ```s1_light_yield_map```, ```get_s2_map_name```: ```s2_light_yield_map```, ```get_fdc_map_name```: ```rz_position_distortion_map```)?

**Comment by jpienaar13** [comment]
Sorry now. Ill have something for you by Monday.

**Comment by pdeperio** [comment]
@coderdj has cleaned up the file-based corrections in https://github.com/XENON1T/hax/pull/141.

So now I guess we need to think of how to implement the MC [here](https://github.com/XENON1T/hax/blob/e079a32107f52774d92f96c9a3fa472c698588e0/hax/treemakers/corrections.py#L75) and [here](https://github.com/XENON1T/hax/blob/e079a32107f52774d92f96c9a3fa472c698588e0/hax/treemakers/corrections.py#L58).

**Comment by pdeperio** [comment]
Fixed by #144, but needs to be tested still.
