### ISSUE TITLE
hax install on xecluster

### ISSUE THREAD

**Issue by cwittweg** [XENON1T/hax#4]
I tried installing hax on my xecluster account, but I got two errors: 

with 

> git clone http://github.com/XENON1T/hax.git

I get

> Initialized empty Git repository in /home/wittweg/hax/.git/
> error: Failed connect to github.com:443; Operation now in progress while accessing https://github.com/XENON1T/hax.git/info/refs
> 
> fatal: HTTP request failed

So I tried a workaround by just doing scp from my local pc. If I run

> python setup.py develop

the installation fails with:

> running develop
> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
>     [Errno 13] Permission denied: '/archive_lngs/common/anaconda3/envs/pax440r5/lib/python3.4/site-packages/test-easy-install-16436.write-test'
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     /archive_lngs/common/anaconda3/envs/pax440r5/lib/python3.4/site-packages/
> 
> Perhaps your account does not have write access to this directory?  If the
> installation directory is a system-owned directory, you may need to sign in
> as the administrator or "root" account.  If you do not have administrative
> access to this machine, you may wish to choose a different installation
> directory, preferably one that is listed in your PYTHONPATH environment
> variable.
> 
> For information on other options, you may wish to consult the
> documentation at:
> 
>   https://pythonhosted.org/setuptools/easy_install.html
> 
> Please make the appropriate changes for your system and try again.

**Comment by JelleAalbers** [comment]
Hi Christian, 

About your first error: did you try it on xecluster01? On xecluster06 you can't get anything from the internet. On xecluster01 you also can't https to most sites because the certificates are so old. Some workarounds for using pip and git are described in pax FAQ:
http://xenon1t.github.io/pax/faq.html#how-do-i-set-up-pax-at-lngs-on-xecluster

About the second error; You don't have write privileges in /archive_lngs/common/anaconda3 (I think only Alfio and/or other computing overlords do). If you want to install your own conda packages you have to first clone the conda environment to your home directory. The instructions for this appear on screen whenever you try to install (or perhaps update) anything with conda rather than pip.

**Comment by cwittweg** [comment]
Works now by using my own pax environment on xecluster and the git workarounds from the pax installation manual. Thanks!
