### ISSUE TITLE
Duplicate columns when using Treemaker

### ISSUE THREAD

**Issue by sanderbreur** [XENON1T/hax#7]
The 'data' from hax now has duplicate column names named: 'índex' . When trying to convert pandas to numpy this gives an error that can be solved with:

`# Convert dataframe to numpy array, so we don't need .values all the time `
`data` = `data.T.groupby(level=0).first().T`
`data = data.to_records(index=False)`
`
Probably every hax.minitrees.TreeMaker one uses adds one 'index' column. There should always only be one 'índex' column in 'data'.

**Comment by ErikHogenbirk** [comment]
Just stumbled on exactly the same issue. In particular, if you want to convert to np.array, you get an error because of this. 

I'm not sure but I think this error comes in somewhere when there is a conversion to a np.array, actually, because this actually create a column called index.

I guess this can be fixed by the following: ```d = df.ix[:,1:].to_records()``` in the place of ```d = df.to_records()``` If I find some time will try to fix myself.

**Comment by sanderbreur** [comment]
Jup, that did the job, thanks!
