### ISSUE TITLE
Add second S2 width to Basics minitrees?

### ISSUE THREAD

**Issue by ErikHogenbirk** [XENON1T/hax#72]
When we want to do a single scatter cut, we mostly cut on the S2 size in some way. However, based on explorations in this note by Tianyu:
https://xecluster.lngs.infn.it/dokuwiki/lib/exe/fetch.php?media=xenon:xenon1t:sim:notes:jhowlett:main_singlescatter_simplified_copy_feb_20_2017.html
it seems that a lot of the second-largest S2s could just be single-electron pile-up and that they can be identified by their with. I could imagine a single scatter cut where we cut not only on the second S2 size, but also on the width. For this it would be great if a property ```largest_other_s2_width``` could be added. It's not critical, it's just a nuisance if we want to use this parameter and have to add it by hand all the time. Let me know what you think. If you disagree I'll drop the issue.

**Comment by JelleAalbers** [comment]
There is now `alt_s2_interaction_s2_range_50p_area` in the Extended minitree, which is what you were asking as long as the largest other s2 is after the main S1. Otherwise I guess the topology is so different we may want to handle the event differently. But perhaps we still need another variable to identify whether this is the case.

After the campaign I hope we get a change to rearrange some minitrees a bit, we're starting to get quite a few of them...

**Comment by feigaodm** [comment]
Close this issue since this branch is there already! Thanks @JelleAalbers
